## Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]
## Switches
set_property PACKAGE_PIN V17 [get_ports {i0}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i0}]
set_property PACKAGE_PIN V16 [get_ports {i1}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i1}]
set_property PACKAGE_PIN W16 [get_ports {i2}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i2}]
set_property PACKAGE_PIN W17 [get_ports {i3}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i3}]
set_property PACKAGE_PIN W15 [get_ports {s0}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {s0}]
set_property PACKAGE_PIN V15 [get_ports {s1}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {s1}]
set_property PACKAGE_PIN W14 [get_ports {reset}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {reset}]
set_property PACKAGE_PIN W13 [get_ports {shiftR}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {shiftR}]
set_property PACKAGE_PIN V2 [get_ports {shiftL}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {shiftL}]
## LEDs
set_property PACKAGE_PIN U16 [get_ports {a0}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {a0}]
set_property PACKAGE_PIN E19 [get_ports {a1}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {a1}]
set_property PACKAGE_PIN U19 [get_ports {a2}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {a2}]
set_property PACKAGE_PIN V19 [get_ports {a3}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {a3}]